export VIRTUAL_ENV_DISABLE_PROMPT=1
export RIVER_DREAMS_RELEASES_DIRECTORY_PATH=$(dirname ${0})/out/releases

setopt promptsubst

PROMPT='$(${RIVER_DREAMS_RELEASES_DIRECTORY_PATH}/LeftPrompt)'
RPROMPT='$(${RIVER_DREAMS_RELEASES_DIRECTORY_PATH}/RightPrompt)'
